/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myphone_CPhone */

#ifndef _Included_com_example_myphone_CPhone
#define _Included_com_example_myphone_CPhone
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myphone_CPhone
 * Method:    Start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_myphone_CPhone_Start
  (JNIEnv *, jobject);

/*
 * Class:     com_example_myphone_CPhone
 * Method:    SendAllSmsMsg
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_example_myphone_CPhone_SendAllSmsMsg
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_example_myphone_CPhone
 * Method:    SendNewInSms
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_example_myphone_CPhone_SendNewInSms
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_example_myphone_CPhone
 * Method:    SendNewOutSms
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_example_myphone_CPhone_SendNewOutSms
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_example_myphone_CPhone
 * Method:    SendNewVoiceMsg
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_example_myphone_CPhone_SendNewVoiceMsg
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_example_myphone_CPhone
 * Method:    SendContacts
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_example_myphone_CPhone_SendContacts
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
